# Generated by Buildr 1.2.10, change to your liking
# Version number for this release
VERSION_NUMBER = "1.0.0"
# Version number for the next release
NEXT_VERSION = "1.0.1"
# Group identifier for your projects
GROUP = "com.lhunath.lyndir.lib"
COPYRIGHT = "Lhunath (C) 2007-2008"

# Dependency Groups
BOUNCYCASTLE    = [ "bouncycastle:bcpg-jdk15:jar:138", "bouncycastle:bcprov-jdk15:jar:138" ]
JTIDY           = "org.hibernate:jtidy-r8:jar:20060801"
HTTPCLIENT      = "commons-httpclient:commons-httpclient:jar:3.1"
JGOODIES        = struct(
    :animation  => "jgoodies:animation:jar:1.2.0",
    :binding    => "jgoodies:binding:jar:2.0.2",
    :forms      => "jgoodies:forms:jar:1.2.0",
    :looks      => "jgoodies:looks:jar:2.1.4",
    :validation => "jgoodies:validation:jar:2.0.0"
)
XOM             = "xom:xom:jar:1.1"
JAVADESKTOP     = struct(
    :timing     => "net.java.dev.timingframework:timingframework:jar:1.0"
)

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2/"
repositories.remote << "http://download.java.net/maven/2/"
repositories.remote << "http://www.ibiblio.org/maven2/"

desc "Lyndir Jlibs"
define "JLibs" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  desc "JLibs Crypto: Cryptography API"
  define "crypto" do
    compile.with project("system"), BOUNCYCASTLE

    package :jar
  end

  desc "JLibs Data: Data Management API"
  define "data" do
    compile.with project("system"), JTIDY, HTTPCLIENT

    package :jar
  end

  desc "JLibs Geo: User Interface API"
  define "geo" do
    compile.with projects("math", "system"), JGOODIES.looks

    package :jar
  end

  desc "JLibs Math: Mathematics API"
  define "math" do
    compile.with project("system")

    package :jar
  end

  desc "JLibs Piccolo: Piccolo ZUI API"
  define "piccolo" do
    compile.with projects("math", "system"),
        artifact("piccolo:piccolo:jar:1.2").from(file("lib/piccolo-1.2.jar")),
        artifact("piccolo:piccolox:jar:1.2").from(file("lib/piccolox-1.2.jar"))

    package :jar
  end

  desc "JLibs Pigeon: Networking API"
  define "pigeon" do
    compile.with project("system"), XOM

    package :jar
  end

  desc "JLibs Shade: The Shade Swing Application Template API"
  define "shade" do
    compile.with projects("geo", "math", "system"), JGOODIES.forms, JAVADESKTOP.timing,
        artifact("net.java.dev.animatedtransitions:animatedtransitions:jar:0.11").from(file("lib/AnimatedTransitions-0.11.jar"))

    package :jar
  end

  desc "JLibs System: Base Utilities and Logging API"
  define "system" do
    package :jar
  end

end
